version: "3.4"

services:

  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./data/mariadb:/var/lib/mysql
      - ./db/create.sql:/docker-entrypoint-initdb.d/init.sql

  front:
    build:
      context: front/
    image: front
    environment:
      VITE_APP_API_HOST: http://localhost:3001
    ports:
      - 3000:3000
    volumes:
      - ./front/www/:/front_app/