version: "3.4"

services:

  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./data/mariadb:/var/lib/mysql
      - ./db/create.sql:/docker-entrypoint-initdb.d/init.sql

  front:
    build:
      context: front/
    image: front
    environment:
      VITE_APP_API_HOST: ${API_URL}
    ports:
      - ${FRONT_APP_PORT}:3000
    volumes:
      - ./front/www/:/front_app/

  api:
    build:
      context: api/
    environment:
      DB_HOST: mariadb
      DB_PORT: ${MYSQL_PORT}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      APP_PORT: 3000
      APP_HOST_REGEX: ${API_HOST}
      SQS_QUEUE_URL: ${AWS_SQS_QUEUE_URL}
      REGION: ${AWS_SQS_REGION}
      ACCESS_KEY: ${AWS_SQS_ACCESS_KEY}
      SECRET: ${AWS_SQS_SECRET}
    ports:
      - ${API_PORT}:3000
    volumes:
      - ./api/www/:/api/