version: "3.5"

services:

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - "80:3000"
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-batch-size: "400"

  loki:
    image: grafana/loki:2.6.1
    restart: unless-stopped
    volumes:
      - loki:/loki
      - ./loki:/etc/loki
    command: -config.file=/etc/loki/loki-config.yml
    ports:
      - "3000:3000"
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-batch-size: "400"

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-batch-size: "400"

volumes:
  grafana:
  loki:
