export default interface GetBothTxsRequest {
    aggregatorId: string,
    fromChainId: string,
    srcTokenAddress: string,
    srcTokenSymbol: string,
    srcTokenDecimals: string,
    toChainId: string,
    dstTokenAddress: string,
    dstTokenSymbol: string,
    dstTokenDecimals: string,
    amount: string,
    slippage: number,
    senderAddress: string,
    receiverAddress: string,
}
