- name: Install dependencies
  hosts: "{{ nodes }}"
  vars:
    - node_version: 16.14
  tasks:
    - name: Install nvm
      shell: >
        curl https://raw.githubusercontent.com/creationix/nvm/v0.39.1/install.sh | sh
        creates=/home/{{ ansible_user_id }}/.nvm/nvm.sh

    - name: Install node
      shell: >
        /bin/bash -c "source ~/.nvm/nvm.sh && nvm install {{ node_version }}"

    - name: Set default
      shell: >
        /bin/bash -c "source ~/.nvm/nvm.sh && nvm alias default {{ node_version }}"
        creates=/home/{{ ansible_user_id }}/.nvm/alias

    - name: Install global npm packages
      shell: >
        /bin/bash -c "source ~/.nvm/nvm.sh && npm install pm2 -g"

    - name: Install APT packages
      become: yes
      become_user: root
      shell: >
        apt update && apt install -y rsync
