name: Deploy Backend - Prod

on:
  push:
    branches: [ 'master' ]
    paths:
      - 'api/www/**'
      - '.github/workflows/api-deploy.yml'
      - '.github/workflows/api-deploy-prod.yml'

jobs:
  workflow-api:
    uses: ./.github/workflows/api-deploy.yml
    secrets:
      EC2_SSH_KEY_API: ${{ secrets.PROD_EC2_SSH_KEY_API }}
      EC2_HOST_API: ${{ secrets.PROD_EC2_HOST_API }}