name: Deploy Backend

on:
  workflow_call:
    secrets:
      EC2_SSH_KEY_API:
        description: 'SSH key to connect to the EC2 instances'
        required: true
      EC2_HOST_API:
        description: 'Hostname of EC2 instance'
        required: true

env:
  root-path: api/www

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    defaults:
      run:
        working-directory: ./${{ env.root-path }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Run Tests
        run: yarn test

      - name: Deploy to EC2
        uses: up9cloud/action-rsync@v1.1
        env:
          KEY: ${{ secrets.EC2_SSH_KEY_API }}
          HOST: ${{ secrets.EC2_HOST_API }}
          USER: admin
          TARGET: /home/admin/code/www
          VERBOSE: true
          ARGS: -az --delete-after --include=dist/*** --include=migrations/*** --include=node_modules/*** --exclude=*
          SOURCE: ./${{ env.root-path }}/
