name: Test contracts

on:
  push:
    paths:
      - 'contracts/www/**'
      - '.github/workflows/contracts.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
      fail-fast: false

    defaults:
      run:
        working-directory: ./contracts/www

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Run Tests
        run: yarn test
