name: Test contracts

on:
  push:
    paths:
      - 'contracts/www/**'
      - '.github/workflows/contracts.yml'

env:
  DOCKER_USER: 1000

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install
        working-directory: ./contracts/www

      - name: Create required folders
        run: mkdir artifacts cache && chmod -R 777 artifacts cache
        working-directory: ./contracts/www

      - name: Build contracts
        run: make compile-contracts

      - name: Run Tests
        run: make test-contracts


