name: Deploy Frontend - Test

on:
  push:
    branches: [ 'master' ]

jobs:
  workflow-front:
    uses: ./.github/workflows/front-deploy.yml
    with:
      environment: test
    secrets:
      AWS_S3_BUCKET: ${{secrets.AWS_S3_BUCKET}}
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      DISTRIBUTION: ${{secrets.DISTRIBUTION}}

