name: Deploy Frontend

on:
  workflow_call:
    inputs:
      api-url:
        required: true
        description: 'URL of the API'
        type: string
    secrets:
      AWS_S3_BUCKET:
        description: 'Bucket name where the build will be deployed'
        required: true
      AWS_ACCESS_KEY_ID:
        description: 'Access key ID of the account with rights'
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: 'Secret key of the account with rights'
        required: true
      DISTRIBUTION:
        description: 'AWS distribution name that needs to be invalidated'
        required: true

env:
  VITE_APP_API_HOST: ${{inputs.api-url}}
  root-path: front/www

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
      fail-fast: false

    defaults:
      run:
        working-directory: ./${{ env.root-path }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Run Tests
        run: yarn test

      - name: Build Project
        run: yarn build

      - name: Archive Build
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ${{ env.root-path }}/dist

  deployment:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Download Dist
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: ${{ env.root-path }}/dist

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: '${{ env.root-path }}/dist'

      - uses: chetan/invalidate-cloudfront-action@v2
        env:
          PATHS: '/*'
          AWS_REGION: 'us-east-1'
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
