name: Deploy Frontend - Prod

on:
  push:
    branches: [ 'master' ]
    paths:
      - 'front/www/**'
      - '.github/workflows/front.yml'
      - '.github/workflows/front-prod.yml'

jobs:
  workflow-front:
    uses: ./.github/workflows/front.yml
    with:
      api-url: https://api.swidge.xyz
    secrets:
      AWS_S3_BUCKET: ${{ secrets.PROD_AWS_S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
      DISTRIBUTION: ${{ secrets.PROD_DISTRIBUTION }}

