name: Deploy Frontend - Prod

on:
  push:
    branches: [ 'master' ]
    paths:
      - 'front/**'
      - '.github/workflows/front.yml'
      - '.github/workflows/front-prod.yml'

jobs:
  workflow-front:
    uses: ./.github/workflows/front.yml
    with:
      environment: prod
      api-url: https://api.swidge.xyz
    secrets:
      AWS_S3_BUCKET: ${{secrets.AWS_S3_BUCKET}}
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      DISTRIBUTION: ${{secrets.DISTRIBUTION}}

