name: Test Frontend

on:
  push:
    branches-ignore:  [ 'master', 'release/**' ]
    paths:
      - 'front/www/**'
      - '.github/workflows/front-test.yml'

env:
  root-path: front/www

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
      fail-fast: false

    defaults:
      run:
        working-directory: ./${{ env.root-path }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Run Tests
        run: yarn test
