name: Deploy Frontend - Prod

on:
  push:
    branches: [ 'master' ]
    paths:
      - front

jobs:
  workflow-front:
    uses: ./.github/workflows/front.yml
    with:
      environment: prod
    secrets:
      AWS_S3_BUCKET: ${{secrets.AWS_S3_BUCKET}}
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      DISTRIBUTION: ${{secrets.DISTRIBUTION}}

