name: Deploy relayer - Prod

on:
  push:
    branches: [ 'master' ]
    paths:
      - 'relayer/**'
      - '.github/workflows/relayer.yml'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    defaults:
      run:
        working-directory: ./relayer

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Run Tests
        run: yarn test

      - name: Build
        run: yarn build

      - name: Deploy to EC2
        uses: up9cloud/action-rsync@v1.1
        env:
          KEY: ${{ secrets.PROD_EC2_SSH_KEY_RELAYER }}
          HOST: ${{ secrets.PROD_EC2_HOST_RELAYER }}
          USER: admin
          TARGET: /home/admin/relayer
          VERBOSE: true
          ARGS: -az --delete-after --include=dist/*** --include=node_modules/*** --exclude=*
          SOURCE: ./relayer/
